# Generated by Django 3.2.6 on 2021-11-22 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_detail',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=200)),
                ('admin_email', models.CharField(max_length=200)),
                ('admin_contact', models.IntegerField()),
                ('admin_image', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_contact', models.IntegerField()),
                ('contact_subject', models.CharField(max_length=500)),
                ('contact_message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_title', models.CharField(max_length=500)),
                ('property_status', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('property_price', models.IntegerField()),
                ('property_sqft_area', models.IntegerField()),
                ('property_bedrooms', models.IntegerField()),
                ('property_bathrooms', models.IntegerField()),
                ('property_address', models.CharField(max_length=500)),
                ('property_city', models.CharField(max_length=200)),
                ('property_state', models.CharField(max_length=200)),
                ('property_zipcode', models.IntegerField()),
                ('property_description', models.CharField(max_length=10000)),
                ('property_others', models.CharField(max_length=500, null=True)),
                ('property_added_date', models.DateField()),
                ('property_is_publish', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subscribe',
            fields=[
                ('subscribe_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscribe_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_contact', models.IntegerField()),
                ('user_image', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_is_active', models.BooleanField(default=False)),
                ('user_title', models.CharField(max_length=200, null=True)),
                ('user_address', models.CharField(max_length=500, null=True)),
                ('user_city', models.CharField(max_length=200, null=True)),
                ('user_state', models.CharField(max_length=200, null=True)),
                ('user_zipcode', models.IntegerField(null=True)),
                ('user_about', models.CharField(max_length=5000, null=True)),
                ('user_facebook', models.CharField(max_length=200, null=True)),
                ('user_twitter', models.CharField(max_length=200, null=True)),
                ('user_instagram', models.CharField(max_length=200, null=True)),
                ('user_linkedin', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_review',
            fields=[
                ('user_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_review_message', models.CharField(max_length=2000)),
                ('user_review_property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.property')),
                ('user_review_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='property_rented_sold',
            fields=[
                ('property_rented_sold_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_rented_sold_date', models.DateField()),
                ('property_rented_sold_duration', models.IntegerField(null=True)),
                ('property_rented_sold_property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.property')),
                ('property_rented_sold_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='property_image',
            fields=[
                ('property_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_image_url', models.ImageField(null=True, upload_to='Property_Image')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_details'),
        ),
        migrations.CreateModel(
            name='bookmarked_property',
            fields=[
                ('bookmarked_property_id', models.AutoField(primary_key=True, serialize=False)),
                ('bookmarked_property_property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.property')),
                ('bookmarked_property_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userside.user_details')),
            ],
        ),
    ]
