# Generated by Django 3.2.6 on 2021-11-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_auto_20211125_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='user_google',
            new_name='user_instagram',
        ),
    ]
