# Generated by Django 3.2.6 on 2021-11-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_rename_user_google_user_details_user_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='p_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
