# Generated by Django 3.2.6 on 2021-11-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_rename_user_google_user_details_user_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='user_image',
            field=models.ImageField(null=True, upload_to='User_Profile_Image'),
        ),
    ]
