# Generated by Django 3.2.6 on 2021-11-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_alter_user_details_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_data',
            name='p_count',
            field=models.IntegerField(null=True),
        ),
    ]
