# Generated by Django 3.2.6 on 2021-12-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_agent_data_p_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_rented_sold',
            name='property_rented_sold_user_id',
            field=models.CharField(max_length=200),
        ),
    ]
