# Generated by Django 3.2.6 on 2021-12-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0006_alter_property_rented_sold_property_rented_sold_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_rented_sold',
            name='property_rented_sold_duration',
        ),
        migrations.RemoveField(
            model_name='property_rented_sold',
            name='property_rented_sold_user_id',
        ),
    ]
