# Generated by Django 3.2.6 on 2021-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0007_auto_20211204_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='property_rented_sold',
        ),
    ]
